### ISSUE TITLE
Strange Exception

### ISSUE THREAD

**Issue by Vierheller** [Vierheller/Organizer#27]
Below exception occures when getting back from EditorActivity to TabActivity and added a new Event.

10-18 20:32:00.625 30597-30597/de.grau.organizer E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: de.grau.organizer, PID: 30597
                                                                   java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131558578, class android.widget.ListView) with Adapter(class de.grau.organizer.adapters.EventsListAdapter)]
                                                                       at android.widget.ListView.layoutChildren(ListView.java:1582)
                                                                       at android.widget.AbsListView$CheckForTap.run(AbsListView.java:4008)
                                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:145)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5938)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

**Comment by gabkol** [comment]
I can't reproduce this exception. So I think it is done..
