### ISSUE TITLE
Search function crashes

### ISSUE THREAD

**Issue by gabkol** [Vierheller/Organizer#40]
E/InputEventReceiver: Exception dispatching input event.
E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI: java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131624123, class android.widget.ListView) with Adapter(class de.grau.organizer.adapters.EventsListAdapter)]
                        at android.widget.ListView.layoutChildren(ListView.java:1593)
                        at android.widget.AbsListView.onTouchUp(AbsListView.java:4184)
                        at android.widget.AbsListView.onTouchEvent(AbsListView.java:3924)
                        at android.view.View.dispatchTouchEvent(View.java:9415)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2310)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2672)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2324)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2672)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2324)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2672)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2324)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2672)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2324)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2672)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2324)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2672)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2324)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2672)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2324)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2672)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2324)
                        at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2453)
                        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1772)
                        at android.app.Activity.dispatchTouchEvent(Activity.java:2875)
                        at android.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:51)
                        at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2414)
                        at android.view.View.dispatchPointerEvent(View.java:9646)
                        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4745)
                        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4603)
                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4108)
                        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4161)
                        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4127)
                        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4273)
                        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4135)
                        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4330)
                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4108)
                        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4161)
                        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4127)
                        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4135)
                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4108)
                        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6562)
                        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6536)
                        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6479)
                        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6734)
                        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                        at android.os.MessageQueue.nativePollOnce(Native Method)
                        at android.os.MessageQueue.next(MessageQueue.java:328)
                        at android.os.Looper.loop(Looper.java:164)
                        at android.app.A

**Comment by avijain7143** [comment]
How did you resolve this issue? please help me out, i am finding the same while filtering the list.

**Comment by Vierheller** [comment]
Hi @avijain7143 . This project was made in scope of a student project that was finished in Oct 2016. I am not 100% sure if this Issue was closed after actually fixing the problem. 

Please tell me if you still have this issue. I will look over the code and do what I can to help you.
